#if !defined(MHDTURBULENCE_SOLOMON_FORTRAN_HPP)
#define MHDTURBULENCE_SOLOMON_FORTRAN_HPP

#if defined(OFFLOAD_BY_OPENMP_TARGET) && !defined(_OPENMP)
#define _OPENMP 202011
#endif

#include <solomon.hpp>

#if defined(OFFLOAD_BY_OPENMP_TARGET)

#undef PRAGMA_ACC_KERNELS
#define PRAGMA_ACC_KERNELS(...)

#undef PRAGMA_ACC_END_KERNELS
#define PRAGMA_ACC_END_KERNELS

#undef PRAGMA_ACC_LOOP
#define PRAGMA_ACC_LOOP(...) PRAGMA_OMP_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO(OMP_TARGET_CLAUSE_DEFAULTMAP(tofrom:scalar) APPEND_ARGS(__VA_ARGS__))

#undef AS_INDEPENDENT
#define AS_INDEPENDENT

#undef PRAGMA_ACC_SERIAL
#define PRAGMA_ACC_SERIAL(...)

#undef PRAGMA_ACC_END_SERIAL
#define PRAGMA_ACC_END_SERIAL

#undef DECLARE_OFFLOADED
#define DECLARE_OFFLOADED(...) PRAGMA_OMP(declare target)

#undef DECLARE_OFFLOADED_END
#define DECLARE_OFFLOADED_END

#undef DECLARE_END_OFFLOADED
#define DECLARE_END_OFFLOADED

#undef USE_DEVICE_DATA_FROM_HOST
#define USE_DEVICE_DATA_FROM_HOST(...)

#undef PRAGMA_ACC_END_HOST_DATA
#define PRAGMA_ACC_END_HOST_DATA

#define SOLOMON_DECLARE_CREATE(...) PRAGMA_OMP(declare target (__VA_ARGS__))
#define SOLOMON_DECLARE_CREATE_ACC_ONLY(...)
#define SOLOMON_DEVICE_TO_HOST(...) MEMCPY_D2H(__VA_ARGS__)
#define SOLOMON_HOST_TO_DEVICE(...) MEMCPY_H2D(__VA_ARGS__)

#else

#define SOLOMON_DECLARE_CREATE(...) PRAGMA_ACC_DECLARE(ACC_CLAUSE_CREATE(__VA_ARGS__))
#define SOLOMON_DECLARE_CREATE_ACC_ONLY(...) PRAGMA_ACC_DECLARE(ACC_CLAUSE_CREATE(__VA_ARGS__))
#define SOLOMON_DEVICE_TO_HOST(...)
#define SOLOMON_HOST_TO_DEVICE(...) MEMCPY_H2D(__VA_ARGS__)

#endif

#define SOLOMON_MPI_D2H(...) MEMCPY_D2H(__VA_ARGS__)
#define SOLOMON_MPI_H2D(...) MEMCPY_H2D(__VA_ARGS__)

#endif
