name: Build FORD Docs

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install ford graphviz mkdocs

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz doxygen

      - name: Build documentation
        working-directory: docs
        run: |
          ford ford-f90acc.md
          ford ford-f90omp.md
          ford ford-f90cpu.md
          doxygen Doxyfile-cpp_omp
          doxygen Doxyfile-cpp_kokkos_device
          doxygen Doxyfile-cpp_kokkos_host
          mkdocs build -f mkdocs.yml --clean

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
